services:
  bingo:
    restart: unless-stopped
    build:
      context: .
      target: final
    env_file: 
      - .prod-env
    cpu_count: 1
    mem_limit: 1g
    ports:
      - '2137:2137'
    volumes:
      - ./data:/bingo/data

