services:
  bingo:
    restart: unless-stopped
    build:
      context: .
      target: final
    env_file: 
      - .env
    cpu_count: 1
    mem_limit: 1g
    ports:
      - '8089:8089'
    volumes:
      - ./data:/bingo/data
    networks:
      - proxy

networks:
  proxy:
    external: true
