services:
  bingo:
    restart: unless-stopped
    build:
      context: .
      target: final
    env_file: 
      - .prod-env
    cpu_count: 1
    mem_limit: 4g
    volumes:
      - ./data:/bingo/data
      - ./static:/bingo/static
    networks:
      - proxy

networks:
  proxy:
    external: true

