// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"

	"github.com/fr-str/bingo/pkg/db/types"
)

type BingoHistory struct {
	Field     string
	Session   string
	Day       int64
	IsSet     sql.NullInt64
	CreatedAt types.RFC3339
	UpdatedAt types.RFC3339
}
