// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"
)

type BingoHistory struct {
	ID        string
	Field     string
	IsSet     sql.NullInt64
	Session   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
